from flask import Flask, render_template

# Import requests library to handle API requests
import requests

app = Flask(__name__)

# app.secret_key = os.environ['flask_secret_key']

# app.config['SESSION_COOKIE_SAMESITE'] = 'None'
# app.config['SESSION_COOKIE_SECURE'] = True

# Fake database to hold data
db = {
  'total_dogs_generated': 0,
}

# Check if key not found in database, then create key
if 'total_dogs_generated' not in db:
  db['total_dogs_generated'] = 0


'''
Add methods allowed to home route 
'''
@app.route('/')
def home():
  return render_template('index.html')

'''
Create a get_dog route
Create a request for a random dog image
Let it render to same home page template
Pass the value of rendered dog image to variable/attribute
'''
@app.route('/get_dog')
def get_dog():
  # get request for random dog image
  response = requests.get('https://dog.ceo/api/breeds/image/random')

  # convert response
  data = response.json() 

  # set random url to dog_img
  dog_image = data['message']

  # increment value of dogs generated by1
  db['total_dogs_generated'] += 1

  return render_template('index.html',
   dog_image=dog_image,
   dogs_generated=db['total_dogs_generated'],)

'''
Create route for logout
'''
@app.route('/logout')
def logout():
  return 'LOGOUT PAGE'

if __name__ == "__main__":
    # Replit server config
    # app.run(debug=True,host='0.0.0.0', port=81)

    # Local server config
    app.run(debug=True)